'''
Script that sets up an SQL agent that fetches results basis user prompts and sends to frontend.
'''
from dotenv import load_dotenv
import os
from langchain_openai import ChatOpenAI
from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits import SQLDatabaseToolkit, create_sql_agent
from langchain_community.tools.sql_database.tool import QuerySQLDatabaseTool
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
import re

load_dotenv()

# load GPT API key
openai_api_key = os.getenv('OPENAI_API_KEY')

# load database credentials
db_password = os.getenv('MYSQL_password')
db_user = os.getenv('DB_USER')
db_localhost = os.getenv('DB_HOST')
db_port = os.getenv('DB_PORT')
db_name = os.getenv('DB_NAME')
uri_db_credentials = f'mysql+pymysql://{db_user}:{db_password}@{db_localhost}:{db_port}/{db_name}'

# setup GPT-5.2 model
model = ChatOpenAI(
    model="gpt-5.2",
    api_key=openai_api_key,
    temperature=0.0, # higher number indicates more randomness in the model's output
    max_tokens=500, #defines the no of words in the model's response
    timeout=30, # max time in sec to wait for model's response
)
# establish database connection to use all tables listed within
db = SQLDatabase.from_uri(uri_db_credentials)

# subclass that inherits from exception used to raise error when current user tries to fetch other user's data.
class AuthorizationError(Exception):
    pass

# subclass SQLDatabaseToolkit to rewrite sql_db_query tool to inject user-scoped view.
class SecureSQLToolkit(SQLDatabaseToolkit):
    userid: int

    # override sql_db_query in get_tools function keeping the other tools as is.
    def get_tools(self):
        '''
        Function to override sql_db_query functionality within SQLDatabaseToolkit to generate SQL query on user-scoped tables.
        :return:
        '''
        tools = super().get_tools()
        new_tools = []

        for tool in tools:
            if tool.name == 'sql_db_query':
                new_tools.append(SecureSQLQueryTool(db=db,userid=self.userid))
            else:
                new_tools.append(tool)
        return new_tools


# subclass QuerySQLDatabaseTool to override sql_db_query function
class SecureSQLQueryTool(QuerySQLDatabaseTool):
    userid: int

    def _run(self,query:str,run_manager=None):

        # intercept secure SQL query generated by the LLM for the current authenticated user.
        query = self._secure_query(query)
        return super()._run(query=query,run_manager=run_manager)

    def _secure_query(self, query: str) -> str:
        query = query.strip().rstrip(";")

        # Allow only SELECT statements
        if not query.upper().startswith("SELECT"):
            raise ValueError("Only SELECT statements are allowed.")

        # Reject dangerous statements
        forbidden = [
            "DROP",
            "DELETE",
            "UPDATE",
            "INSERT",
            "ALTER",
            "TRUNCATE",
        ]

        for keyword in forbidden:
            if re.search(rf"\b{keyword}\b", query, re.IGNORECASE):
                raise ValueError(f"{keyword} statements are forbidden.")

        # Restrict expenses table (user-scope). If already scoped ignore.
        if re.search(r"\bFROM\s+expenses\b", query, re.IGNORECASE):

            # check if already scoped to current user
            if re.search(rf"\bid\s*=\s*{self.userid}\b", query, re.IGNORECASE):
                return query

            clause_match = re.search(r"\b(GROUP\s+BY|ORDER\s+BY|HAVING|LIMIT)\b",query,re.IGNORECASE)

            # if query not user-scoped execute below codes.
            if re.search(r"\bWHERE\b", query, re.IGNORECASE):
                # if there exists GROUP BY/HAVING/ORDER BY etc, WHERE id = (user_id) to be added before them to have a proper SQL query.
                if clause_match:
                    idx = clause_match.start()
                    query = query[:idx].rstrip() + f" AND id = {self.userid} " + query[idx:].lstrip()
                else:
                    query = query.rstrip() + f" AND id = {self.userid}"
            else:
                if clause_match:
                    idx = clause_match.start()
                    query = query[:idx].rstrip() + f" WHERE id = {self.userid} " + query[idx:].lstrip()
                else:
                    query += f" WHERE id = {self.userid}"

        if query[-1]!=";":
            query += ";"
        return query


class LLM:
    userid = ""
    # SQL-agent memory context
    agent_memory_context = """
        Use the following conversation context only if relevant.
        {memory_context}
        
        Current user question.
        {query} 
    """

    # chat prompt
    chat_prompt = """
        {system_prompt}
        
        Answer conversationally without querying database.
        
        Conversation Context:
        {memory_context}
        
        User:
        {query}
    """

    # clarify prompt
    clarify_prompt = """
        Ask one short clarification question only.
        
        Conversation Context:
        {memory_context}
        
        User:
        {query}
    """

    # setup a detailed system prompt to customise agent behaviour.
    system_prompt = """
        You are EXPENSI, the Simpex expense assistant.

        You help the authenticated user with:
        1. conversational replies,
        2. expense insights from memory/context,
        3. SQL queries only when required.
        
        Current authenticated user id: {userid}
        
        Rules:
        - Do not display '*' around answers please.
        - Do not show database column names.
        - Do not display extra information. Answer to the point always.
        - First decide whether the user's message needs database access.
        - Do NOT query the database for greetings, identity questions, capability questions, or responses that can be answered from conversation context.
        - Use conversation context when the current message is a follow-up, such as:
          "same period", "that category", "compare with previous one", "what about this month", "why?", "show it again".
        - Only generate SQL when fresh user-specific expense data is needed.
        - If the request is ambiguous and context is insufficient, ask a concise clarifying question instead of querying.
        - Never perform INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE to the database if user asks you to.
        - Never access data for any user except the authenticated user.
        - If you generate SQL, always scope by the authenticated user id.
        """

    router_prompt = ChatPromptTemplate.from_messages([
                ("system", """
                    You are a routing assistant for an expense tracker.
                
                    Classify the user request into exactly one label:
                    - chat -> no database needed
                    - clarify -> ambiguous, ask short clarification
                    - sql -> needs fresh data from database
                
                    Use chat when the message is:
                    - greeting
                    - small talk
                    - asks who you are / what you can do
                    - asks to explain a previous answer already present in memory
                    - follow-up answerable from memory context alone
                
                    Use sql when the message needs:
                    - totals, sums, counts, averages
                    - category-wise or period-wise spending
                    - comparisons across time
                    - latest user-specific expense data
                
                    Use clarify when:
                    - message depends on missing reference such as "same period", "that category", "compare this"
                    - memory context is insufficient
                
                    Return only one word: chat, clarify, or sql.
                    """),
                ("human", """
                    Conversation context:
                    {memory_context}
                
                    User message:
                    {query}
                    """)
    ])

    def __init__(self, userid : str):
        self.userid = userid
        self.system_prompt = LLM.system_prompt.format(userid=self.userid)
        self.router_chain = self.router_prompt | model | StrOutputParser()

    def _build_memory_context(self, short_memory : dict | None = None):
        '''
        Function that builds memory context for the LLM using last chat history.
        :return:
        '''
        if short_memory is None:
            short_memory = {}
        recent_messages = short_memory.get("recent_messages",[])
        recent_text = []

        for msg in recent_messages:
            role = msg.get("role","user")
            content = msg.get("content","").strip()
            if content:
                recent_text.append(f"{role}: {content}")

        context_parts = []
        if recent_text:
            context_parts.append(f"Recent Messages:\n{recent_text}")

        return '\n\n'.join(context_parts)

    def route_query(self, query: str, memory_context : str):
        '''
        Function that classifies user-query into either "chat"/"clarify"/"sql".
        :param query:
        :param memory_context:
        :return:
        '''
        route = self.router_chain.invoke({
            "memory_context": memory_context,
            "query": query
        }).strip().lower()

        if route not in ["chat","clarify","sql"]:
            route = "clarify"
        return route

    def check_for_id_other_than_current_user(self,final_input : str) -> bool:
        '''
        Function that checks for presence of "id" in user query.
        If present it checks whether user seeks to find information about other user's in which case
        the agent denies access.
        :param
        final_input:
        user_id:
        :return:
        '''
        id_check = re.search(r"\bid\s*=\s*(\d+)", final_input, re.IGNORECASE)
        if id_check and (id_check.group(0)[3:] != self.userid):
            return True
        return False

    def send_response_to_user_prompt(self, query : str, short_memory : dict | None = None):
        '''
        Function that sends a response to a user's query fetching necessary data from the database only if query is related
        to the current logged in user else not.
        Also it uses an LLM-classifier to classify user-prompt context into "clarify","chat" or "sql" and calls SQL-agent only when
        context is "sql" otherwise it responds from either system-prompt or memory.
        :param
        query: User question
        short_memory: dictionary indicative of all prior messages exchanged between user and agent in the current session.
        :return:
        '''

        if short_memory is None:
            short_memory = {}

        memory_context = self._build_memory_context(short_memory)
        final_input = self.agent_memory_context.format(memory_context=memory_context,query=query) if memory_context else query

        # Check whether user intends to find out information about other user's in the database.
        if self.check_for_id_other_than_current_user(final_input):
            yield "I can only access your own expenses.\n I cannot retrieve another user's data.\n Please keep questions within your data only."
            return

        # route user-prompt to classify it to either "chat","clarify" or "sql"
        route = self.route_query(final_input, memory_context)
        if route == "chat":
            response = model.invoke(self.chat_prompt.format(system_prompt=self.system_prompt,memory_context=memory_context,query=query))
            yield response.content
            return
        elif route == "clarify":
            response = model.invoke(self.clarify_prompt.format(system_prompt=self.system_prompt,memory_context=memory_context,query=query))
            yield response.content
            return

        # setup db with user-scoped tables
        user_db = SQLDatabase.from_uri(uri_db_credentials,include_tables=['expenses'])

        # setup tools for user_db so to generate tools pertaining to user-scoped tables only. This includes sql_db_query, sql_db_query_checker, sql_db_list_tables etc.
        tools = SecureSQLToolkit(db=user_db,llm=model,userid=int(self.userid))

        # setup a tool-based SQL agent and not an older text-based ReAct one.
        sql_agent = create_sql_agent(
            llm=model,
            toolkit=tools,
            prefix=self.system_prompt,
            agent_type='tool-calling',
            verbose=True,
        )

        # LLM invoked iff query pertains to current logged user.
        result = sql_agent.invoke({'input': final_input})
        yield result['output']

# if __name__ == '__main__':
#     llm_obj = LLM('3')
#     print(list(llm_obj.send_response_to_user_prompt('Can you fetch my expenses and display that in tabular form?')))